name: quantumenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - flask
  - requests
  - matplotlib
  - plotly
  - pytest
  - jupyter
  - pip
  - pip:
      - flask-cors   # needed for backend API CORS
