import { useState } from 'react'
import { Wrench, Globe, Shuffle, Lock, Calculator } from 'lucide-react'
import FPGASimulation from './FPGASimulation'
import ANUSimulation from './ANUSimulation'
import HybridSimulation from './HybridSimulation'
import CryptographicSimulation from './CryptographicSimulation'

const TechniqueSimulations = ({ apiUrl }) => {
  const [activeSimulation, setActiveSimulation] = useState('fpga')

  const simulations = {
    fpga: {
      name: 'FPGA Quantum Simulation',
      component: FPGASimulation,
      icon: Wrench,
      color: '#9333ea'
    },
    anu: {
      name: 'ANU Quantum API',
      component: ANUSimulation,
      icon: Globe,
      color: '#a855f7'
    },
    hybrid: {
      name: 'Hybrid Mode',
      component: HybridSimulation,
      icon: Shuffle,
      color: '#c084fc'
    },
    cryptographic: {
      name: 'Cryptographic',
      component: CryptographicSimulation,
      icon: Lock,
      color: '#d946ef'
    },
  }

  const ActiveComponent = simulations[activeSimulation].component

  const renderTechniqueDescription = (technique) => {
    const descriptions = {
      fpga: {
        title: "FPGA Quantum Simulation",
        explanation: [
          "Field-Programmable Gate Arrays (FPGAs) can simulate quantum mechanical noise sources at extremely high speeds (50+ Mbps). This technique models the fundamental randomness found in quantum systems without requiring actual quantum hardware.",
          "The simulation incorporates multiple noise sources: thermal noise from electronic components at the quantum level, shot noise from individual photons or electrons, and quantum interference patterns that create truly unpredictable outcomes.",
          "Advanced algorithms like von Neumann debiasing are applied to remove any statistical biases, ensuring the output is uniformly random. The FPGA's parallel processing capabilities allow for real-time generation of high-quality entropy suitable for cryptographic applications."
        ]
      },
      anu: {
        title: "ANU Quantum API",
        explanation: [
          "The Australian National University (ANU) Quantum Random Numbers Server provides access to real quantum random numbers generated by measuring quantum fluctuations in a vacuum state - the quantum mechanical 'empty space' that still contains energy fluctuations.",
          "Using advanced laser interferometry, ANU measures the quantum vacuum fluctuations in real-time. These fluctuations are fundamentally unpredictable according to quantum mechanics - not just difficult to predict, but physically impossible to predict even with perfect knowledge of the system.",
          "Each measurement captures the inherent randomness of quantum mechanics itself. However, due to the specialized equipment and research nature of this service, it's rate-limited to preserve the resource for scientific research (1 request per minute)."
        ]
      },
      hybrid: {
        title: "Hybrid Validation Mode",
        explanation: [
          "The Hybrid mode combines the high-speed generation capabilities of FPGA simulation with the scientific validation of real quantum measurements from ANU. This provides the best of both worlds: speed and authenticity.",
          "The system primarily uses FPGA-generated quantum noise for continuous operation, but periodically validates the quality and randomness characteristics against true quantum measurements from ANU's vacuum fluctuation detector.",
          "Statistical analysis continuously compares the FPGA output with quantum reference data, automatically adjusting parameters to maintain quantum-grade randomness. This ensures enterprise-level performance while maintaining the highest standards of cryptographic security."
        ]
      },
      cryptographic: {
        title: "Cryptographically Secure Randomness",
        explanation: [
          "This technique uses the operating system's built-in cryptographically secure random number generator, which combines multiple entropy sources from your computer's hardware and environment: mouse movements, keyboard timings, disk seek times, and thermal noise from electronic components.",
          "The OS continuously collects unpredictable events and feeds them into entropy pools that are cryptographically processed to produce unbiased random numbers. Modern operating systems use sophisticated algorithms to ensure the output passes rigorous statistical tests for randomness.",
          "While not quantum-based, this method is battle-tested and forms the foundation of most internet security. It's the gold standard for software-based randomness and is used by banks, governments, and security systems worldwide."
        ]
      }
    }

    const desc = descriptions[technique]
    return (
      <div className="technique-detailed-description">
        <h3>{desc.title}</h3>
        {desc.explanation.map((paragraph, index) => (
          <p key={index}>{paragraph}</p>
        ))}
      </div>
    )
  }

  return (
    <div className="technique-simulations">
      <div className="concept-overview">
        <h1>Quantum Random Number Generation</h1>
        <div className="concept-explanation">
          <p>
            True randomness is fundamental to cryptography, simulations, and secure communications. Unlike traditional computer algorithms that produce predictable "pseudo-random" sequences, quantum random number generators harness the inherent uncertainty of quantum mechanical processes to create genuinely unpredictable values.
          </p>
          <p>
            Quantum mechanics tells us that certain physical processes are fundamentally random - not just difficult to predict, but truly non-deterministic. When we measure quantum states like photon polarization or electron spin, the outcome is governed purely by probability, making it impossible to predict even with perfect knowledge of the system.
          </p>
          <p>
            This dashboard demonstrates different approaches to quantum random generation, from high-speed FPGA simulations of quantum noise to direct measurement of real quantum phenomena through research-grade hardware.
          </p>
        </div>
      </div>

      <div className="simulations-header">
        <h2>Interactive Technique Simulations</h2>
        <p>Explore how each method generates truly random numbers through quantum processes</p>
      </div>

      <div className="simulation-tabs">
        {Object.entries(simulations).map(([key, sim]) => {
          const IconComponent = sim.icon
          return (
            <button
              key={key}
              className={`simulation-tab ${activeSimulation === key ? 'active' : ''}`}
              onClick={() => setActiveSimulation(key)}
              style={{ '--tab-color': sim.color }}
            >
              <IconComponent className="tab-icon" size={20} />
              <span className="tab-name">{sim.name}</span>
            </button>
          )
        })}
      </div>

      <div className="technique-description">
        {renderTechniqueDescription(activeSimulation)}
      </div>

      <div className="simulation-content-container">
        <div className="simulation-content">
          <ActiveComponent apiUrl={apiUrl} />
        </div>
      </div>

      <div className="simulation-comparison">
        <h3>Technique Comparison</h3>
        <div className="comparison-grid">
          <div className="comparison-item">
            <h4><Wrench size={20} /> FPGA Simulation</h4>
            <div className="pros-cons">
              <div className="pros">
                <strong>Pros:</strong>
                <ul>
                  <li>Very fast (50+ Mbps)</li>
                  <li>Always available</li>
                  <li>Simulates quantum physics</li>
                  <li>No network dependency</li>
                </ul>
              </div>
              <div className="cons">
                <strong>Cons:</strong>
                <ul>
                  <li>Simulated, not real quantum</li>
                  <li>Based on software algorithms</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="comparison-item">
            <h4><Globe size={20} /> ANU Quantum API</h4>
            <div className="pros-cons">
              <div className="pros">
                <strong>Pros:</strong>
                <ul>
                  <li>Real quantum hardware</li>
                  <li>Research-grade quality</li>
                  <li>Truly unpredictable</li>
                  <li>Scientifically validated</li>
                </ul>
              </div>
              <div className="cons">
                <strong>Cons:</strong>
                <ul>
                  <li>⚠️ SEVERE: Only 1 req/minute</li>
                  <li>Network latency (150+ ms)</li>
                  <li>Requires special access</li>
                  <li>Not practical for apps</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="comparison-item">
            <h4><Shuffle size={20} /> Hybrid Mode</h4>
            <div className="pros-cons">
              <div className="pros">
                <strong>Pros:</strong>
                <ul>
                  <li>Speed + validation</li>
                  <li>Quality assurance</li>
                  <li>Best of both worlds</li>
                  <li>Continuous monitoring</li>
                </ul>
              </div>
              <div className="cons">
                <strong>Cons:</strong>
                <ul>
                  <li>Complex implementation</li>
                  <li>Still needs internet</li>
                  <li>Higher computational cost</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="comparison-item">
            <h4><Lock size={20} /> Cryptographic</h4>
            <div className="pros-cons">
              <div className="pros">
                <strong>Pros:</strong>
                <ul>
                  <li>OS-level security</li>
                  <li>Battle-tested</li>
                  <li>Multiple entropy sources</li>
                  <li>Industry standard</li>
                </ul>
              </div>
              <div className="cons">
                <strong>Cons:</strong>
                <ul>
                  <li>Not quantum-based</li>
                  <li>Depends on system events</li>
                  <li>Can be slower on low-entropy systems</li>
                </ul>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  )
}

export default TechniqueSimulations